name: Run Sitespeed Test & Publish Report

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-sitespeed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Run ID (human-readable date)
        run: |
          echo "RUN_ID=$(date +%Y-%m-%d_%H-%M-%S)" >> $GITHUB_ENV
          echo "TIMESTAMP=$(date +%s)" >> $GITHUB_ENV

      - name: Setup InfluxDB plugin
        run: |
          # Create sitespeed.io plugins directory structure
          mkdir -p plugins
          
          # Clone the official plugin repository directly to the plugins directory
          git clone https://github.com/sitespeedio/plugin-influxdb.git plugins/influxdb
          
          # Install plugin dependencies
          cd plugins/influxdb && npm install && cd ../..
          
          # Debug - List directory structure
          echo "--- Plugin directory contents ---"
          find plugins -ls
          echo "--- End plugin directory contents ---"

      - name: Setup and Start InfluxDB
        run: |
          mkdir -p .influxdb-data # Isolate InfluxDB data
          docker network create sitespeed-net
          docker run -d --name influxdb \
            --network sitespeed-net \
            -p 8086:8086 \
            -v "$(pwd)/.influxdb-data:/var/lib/influxdb2" \ # Use isolated data directory
            -e DOCKER_INFLUXDB_INIT_MODE=setup \
            -e DOCKER_INFLUXDB_INIT_USERNAME=surendracv \
            -e DOCKER_INFLUXDB_INIT_PASSWORD=Vegastack@@ \
            -e DOCKER_INFLUXDB_INIT_ORG=vega \
            -e DOCKER_INFLUXDB_INIT_BUCKET=sitespeed \
            -e DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${{ secrets.INFLUXDB_TOKEN }} \
          influxdb:latest
          
          echo "Waiting for InfluxDB to start..."
          sleep 10 # Give InfluxDB some time to initialize

      - name: Run Sitespeed.io Test
        run: |
          mkdir -p sitespeed-result # Ensure this directory is created by the runner user
          docker run --rm \
            --user "$(id -u):$(id -g)" \ # Run as current host user to ensure correct file ownership
            --network sitespeed-net \
            --shm-size=1g \
            -v "$(pwd)/sitespeed-result:/sitespeed.io" \ # Mount the correct results directory
            -v "$(pwd)/plugins:/plugins" \
            sitespeedio/sitespeed.io:latest \
            https://vegastack.com \
            -d 2 \
            --outputFolder /sitespeed.io/${{ env.RUN_ID }} \
            --plugins.add /plugins/influxdb \
            --influxdb.host influxdb \
            --influxdb.version 2 \
            --influxdb.organisation vega \
            --influxdb.token ${{ secrets.INFLUXDB_TOKEN }} \
            --influxdb.bucket sitespeed

      # - name: setting up permissions
      #   run: |
      #     sudo chown -R $USER:$USER .

      - name: Update report-mapping.json (append & sort desc)
        run: |
          MAPPING_FILE="sitespeed-result/report-mapping.json"
          REPORT_URL="https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/${{ env.RUN_ID }}/index.html"
          
          # Ensure the mapping file exists and is valid JSON
          if [ ! -f "$MAPPING_FILE" ] || ! jq empty "$MAPPING_FILE" 2>/dev/null; then
            echo "Initializing $MAPPING_FILE with an empty array."
            echo "[]" > "$MAPPING_FILE"
          fi
          
          jq --arg id "${{ env.RUN_ID }}" \
             --arg url "$REPORT_URL" \
             --argjson ts_num "$(date +%s)" \ # Pass timestamp as a number
             '. += [{"run_id": $id, "timestamp": $ts_num, "report_url": $url}] | sort_by(.timestamp) | reverse' \
             "$MAPPING_FILE" > tmp.json && mv tmp.json "$MAPPING_FILE"
          echo "--- report-mapping.json contents ---"
          cat "$MAPPING_FILE"
          echo "--- End report-mapping.json contents ---"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PERSONAL_GITHUB_TOKEN }} 
          publish_dir: ./sitespeed-result
          publish_branch: gh-pages
          # user_name: 'github-actions[bot]' 
          # user_email: 'github-actions[bot]@users.noreply.github.com' 
          # force_orphan: true 
