name: Run Sitespeed Test & Publish Report

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-sitespeed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Run ID (human-readable date)
        run: |
          echo "RUN_ID=$(date +%Y-%m-%d_%H-%M-%S)" >> $GITHUB_ENV
          echo "TIMESTAMP=$(date +%s)" >> $GITHUB_ENV
      
      - name: Setup InfluxDB plugin
        run: |
          # Create sitespeed.io plugins directory structure
          mkdir -p plugins
          
          # Clone the official plugin repository directly to the plugins directory
          git clone https://github.com/sitespeedio/plugin-influxdb.git plugins/influxdb
          
          # Install plugin dependencies
          cd plugins/influxdb && npm install && cd ../..
          
          # Debug - List directory structure
          find plugins -type f | sort

      - name: installing influx
        run: | 
          sudo docker run -d --name influxdb \
            -p 8086:8086 \
            -v $PWD:/var/lib/influxdb2 \
            -e DOCKER_INFLUXDB_INIT_MODE=setup \
            -e DOCKER_INFLUXDB_INIT_USERNAME=surendracv \
            -e DOCKER_INFLUXDB_INIT_PASSWORD=Vegastack@@ \
            -e DOCKER_INFLUXDB_INIT_ORG=vega \
            -e DOCKER_INFLUXDB_INIT_BUCKET=sitespeed \
            -e DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${{ secrets.INFLUXDB_TOKEN }} \
            influxdb:latest
          sudo apt install net-tools 
          netstat -nl
        
      - name: Run Sitespeed.io Test
        run: |
          pwd
          sudo mkdir -p sitespeed-result
          sudo docker run --rm \
            --shm-size=1g \
            -v "$(pwd)/sitespeed-result:/sitespeed.io" \
            -v "$(pwd)/plugins:/plugins" \
            sitespeedio/sitespeed.io:latest \
            https://vegastack.com \
            -d 2 \
            --outputFolder /sitespeed.io/${{ env.RUN_ID }} \
            --plugins.add /plugins/influxdb \
            --influxdb.host 0.0.0.0 \
            --influxdb.version 2 \
            --influxdb.organisation vega \
            --influxdb.token ${{ secrets.INFLUXDB_TOKEN }} \
            --influxdb.bucket sitespeed

      - name: Update report-mapping.json (append & sort desc)
        run: |
          MAPPING_FILE="sitespeed-result/report-mapping.json"
          REPORT_URL="https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/${{ env.RUN_ID }}/index.html"
          if [ ! -f "$MAPPING_FILE" ]; then
            echo "[]" > $MAPPING_FILE
          fi
          jq --arg id "${{ env.RUN_ID }}" --arg url "$REPORT_URL" --arg ts "${{ env.TIMESTAMP }}" \
            '. += [{"run_id": $id, "timestamp": $ts | tonumber, "report_url": $url}] | sort_by(.timestamp) | reverse' \
            $MAPPING_FILE > tmp.json && mv tmp.json $MAPPING_FILE

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          publish_dir: ./sitespeed-result
          publish_branch: gh-pages
